name: "Feature Request"
description: "Suggest a new feature or enhancement for the show-file-tree package"
title: "[FEATURE]: "
labels:
  - "enhancement"

body:
  - type: input
    id: summary
    attributes:
      label: "🔑 Short Summary / Problem Statement"
      description: "Provide a concise description of the problem you want to solve."
      placeholder: "e.g., Add interactive network graph for dataset relationships"
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: "💡 Proposed Solution / Feature Description"
      description: "Explain what feature or functionality you want to add."
      placeholder: |
        - Add a function `show_dataset_graph()` that generates an interactive network graph
        - Supports multiple datasets, showing joins and relationships
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: "🎯 Use Case / Motivation"
      description: "Why is this feature useful? Who benefits from it?"
      placeholder: |
        Helps data analysts quickly understand relationships between datasets
        without manually inspecting column names or data types
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "🔄 Alternatives Considered (if any)"
      description: "Have you tried other approaches? Why aren’t they enough?"
      placeholder: |
        - Manual merging and visualization in Jupyter notebook
        - Using third-party visualization tools (complex setup)
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "📎 Additional Context / References"
      description: "Optional: Mockups, related PRs/issues, screenshots, links, references"
      placeholder: |
        - See related issue #12 for initial dataset graph discussion
        - Mockup image attached
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "⚠️ Priority / Importance"
      description: "Select the priority of this feature request"
      options:
        - "Low"
        - "Medium"
        - "High"
        - "Critical"
    validations:
      required: false

  - type: checkboxes
    id: affected_modules
    attributes:
      label: "🧩 Affected Modules / Components"
      description: "Select modules this feature would touch"
      options:
        - label: "CLI (cli.py)"
        - label: "Tree Builder (tree_builder.py)"
        - label: "Tree Renderer (tree_renderer.py)"
        - label: "Markdown Export (md_exporter.py)"
        - label: "Notes Manager (notes_manager.py)"
        - label: "New module"
        - label: "Other"
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: "🔗 Dependencies / Requirements"
      description: "Optional: Any libraries or datasets required for this feature"
      placeholder: |
        - NetworkX for graph
        - Plotly for interactive visualization
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "✅ Pre-Submission Checklist"
      description: "Please confirm before submitting"
      options:
        - label: "Problem clearly described"
          required: true
        - label: "Proposed solution explained"
          required: true
        - label: "Use case/motivation provided"
          required: true
        - label: "Checked for similar existing features"
          required: true
        - label: "Included references or mockups (if applicable)"
          required: false
    validations:
      required: true
