name: Greetings
# https://github.com/marketplace/actions/first-interaction
# https://github.com/Borda/kaggle_SandBox/blob/main/.github/workflows/greetings.yml

on: [issues, pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hi! Thanks for your contribution on the show-file-tree Python package. Share this repo with all your friends — great first issue!"
          pr-message: "Hey, thanks for the input! Please give us a bit of time to review it! If you like the show-file-tree Python package, share this repo with your friends!"
